import type { PlanBlock } from "./types";

export const PLAN: PlanBlock[] =[
{id:"A",name:"Bloque A · Reconstruir la base",wk:"Semanas 1–6",goal:"Cerrar los agujeros de B1 que arrastras desde el colegio. Al final del bloque los tiempos verbales y las preposiciones dejan de costarte tiempo.",weeks:[
 {n:1,t:"Tiempos de presente y pasado, sin dudar",gram:["Present simple vs continuous (estado vs acción)","Past simple: verbos irregulares de alta frecuencia","Adverbios de frecuencia y su posición"],lex:["Rutina profesional y describir tu trabajo","50 verbos irregulares más frecuentes"],skill:["Listening: identificar la idea general antes de los detalles"],tasks:["Diagnóstico completo (Módulo 02) y anotar las 5 áreas más bajas","Gramática: unidades 1 y 18","Vocabulario: 40 tarjetas del mazo Núcleo B1","Escribir 120 palabras: What I do at work (Writing, tarea 1)","Speaking Parte 1 en voz alta, 2 min, sobre tu trabajo"]},
 {n:2,t:"Present perfect: el gran divorcio del español",gram:["Present perfect vs past simple","for / since / already / yet / just / still","Marcadores temporales que obligan a past simple"],lex:["Experiencias y logros profesionales","Colocaciones con have / take / make"],skill:["Reading: skimming en 90 segundos"],tasks:["Gramática: unidades 2 y 3","20 ítems de Use of English (transformaciones)","Vocabulario: 40 tarjetas + repaso de las falladas","Escribir un correo informal de 100 palabras","Registrar 5 errores en el Módulo 11"]},
 {n:3,t:"Futuros y planes",gram:["will vs going to vs present continuous","Future time clauses: when / as soon as + presente","Ofrecimientos, predicciones y decisiones espontáneas"],lex:["Planes, plazos y compromisos","Vocabulario de proyecto y entrega"],skill:["Listening: predicción antes de escuchar"],tasks:["Gramática: unidad 4","Vocabulario: 40 tarjetas del mazo Colocaciones","30 min de podcast con transcript","Escribir 140 palabras sobre tus planes a 12 meses","Speaking Parte 1 grabado y transcrito"]},
 {n:4,t:"Modales de obligación, permiso y consejo",gram:["must / have to / don't have to / mustn't","should / ought to / had better","can / could / be allowed to"],lex:["Normas, políticas internas y permisos","Lenguaje de sugerencia educada"],skill:["Reading: preguntas de opción múltiple, técnica de descarte"],tasks:["Gramática: unidad 8","Elegir examen objetivo y fijar fecha (Módulo 01)","Vocabulario: 40 tarjetas","20 ítems de open cloze","Speaking: dar tres consejos a un colega, 90 s"]},
 {n:5,t:"Preposiciones dependientes",gram:["Verbo + preposición de alta frecuencia","Adjetivo + preposición","Sustantivo + preposición"],lex:["60 combinaciones fijas más frecuentes en el examen"],skill:["Use of English: la parte 2 vive de preposiciones y artículos"],tasks:["Gramática: unidad 15","Vocabulario: mazo Preposiciones completo, dos pasadas","24 ítems de open cloze","Escribir 150 palabras y subrayar cada preposición usada","Revisar cuaderno de errores"]},
 {n:6,t:"Consolidación y primer control",gram:["Repaso activo de las unidades 1–8","Contraste sistemático present perfect / past simple"],lex:["Repaso de las tarjetas en caja 1 y 2"],skill:["Gestión del tiempo: cuánto tardas realmente por parte"],tasks:["Simulacro completo (Módulo 10) y anotar la puntuación","Reescribir dos textos anteriores aplicando la corrección recibida","Vocabulario: vaciar la caja 1","Revisar todas las áreas con menos de 70% en el radar","Speaking Parte 2: monólogo de 1 minuto con cronómetro"]}]},
{id:"B",name:"Bloque B · Del B1 sólido al B2 inicial",wk:"Semanas 7–12",goal:"Aparecen las estructuras que el examinador busca para dar B2: condicionales, pasiva, reported speech y un léxico que deja de ser genérico.",weeks:[
 {n:7,t:"Condicionales 0, 1 y 2",gram:["Estructura y uso de los tres primeros condicionales","unless / as long as / provided that","would en el condicional 2"],lex:["Hipótesis y consecuencias","Verbos de decisión y riesgo"],skill:["Writing: párrafo de opinión con ejemplo y consecuencia"],tasks:["Gramática: unidad 5 (parte 1)","Vocabulario: 40 tarjetas del mazo Núcleo B2","16 transformaciones con palabra clave","Escribir 160 palabras: una decisión difícil","Speaking: responder 5 preguntas hipotéticas"]},
 {n:8,t:"Condicional 3, mixtos y arrepentimientos",gram:["Tercer condicional","Condicionales mixtos","wish / if only / should have"],lex:["Errores, aprendizajes y correcciones"],skill:["Listening: inferir actitud y opinión del hablante"],tasks:["Gramática: unidades 5 (parte 2) y 6","20 transformaciones","Vocabulario: 40 tarjetas","Escribir 170 palabras sobre un error del que aprendiste","Registrar 5 errores nuevos"]},
 {n:9,t:"Voz pasiva en todos sus tiempos",gram:["Pasiva en presente, pasado, perfecto y con modales","Cuándo el inglés prefiere la pasiva y el español la impersonal con se","by + agente: cuándo se omite"],lex:["Procesos, procedimientos y descripciones técnicas"],skill:["Reading: textos informativos y datos"],tasks:["Gramática: unidad 9","Reescribir 15 frases activas en pasiva","Vocabulario: 40 tarjetas","Escribir un informe breve de 160 palabras en pasiva","Simulacro parcial: solo Use of English"]},
 {n:10,t:"Estilo indirecto",gram:["Backshift de tiempos","Cambios de pronombre, tiempo y lugar","Verbos introductorios: admit, deny, suggest, warn, promise"],lex:["Verbos de habla y matiz","Reuniones y acuerdos"],skill:["Listening: tomar notas mientras escuchas"],tasks:["Gramática: unidad 10","Reportar 12 diálogos cortos","Vocabulario: 40 tarjetas del mazo Phrasal verbs","Resumir en 120 palabras un vídeo que hayas visto","Speaking Parte 3: negociar con un compañero imaginario"]},
 {n:11,t:"Gerundio, infinitivo y verbos que cambian de significado",gram:["Verbos seguidos de -ing / to","stop, remember, forget, try, mean, regret","Preposición + -ing"],lex:["Hábitos, intenciones y cambios de plan"],skill:["Use of English: por qué la parte 4 castiga el verbo mal elegido"],tasks:["Gramática: unidad 12","20 transformaciones enfocadas en verbo + patrón","Vocabulario: 40 tarjetas","Escribir 180 palabras: un hábito que cambiaste","Revisar cuaderno de errores y clasificar por categoría"]},
 {n:12,t:"Control de medio curso",gram:["Repaso de unidades 5, 6, 9, 10 y 12"],lex:["Repaso de cajas 1 a 3 completas"],skill:["Diagnóstico de resistencia: dos partes seguidas sin pausa"],tasks:["Repetir el diagnóstico (Módulo 02) y comparar con la semana 1","Simulacro completo cronometrado","Escribir las dos tareas de Writing en 80 minutos reales","Speaking: las cuatro partes seguidas, grabadas","Ajustar el plan: si el radar sigue bajo en un área, repetir su unidad"]}]},
{id:"C",name:"Bloque C · Precisión y rango B2",wk:"Semanas 13–18",goal:"El salto real: estructuras complejas, léxico preciso y textos que suenan escritos por alguien que piensa en inglés, no que traduce.",weeks:[
 {n:13,t:"Modales de deducción y modales perfectos",gram:["must / might / could / can't + infinitivo","must have / can't have / should have + participio","Grados de certeza"],lex:["Especulación y probabilidad","Adverbios de grado: presumably, apparently, arguably"],skill:["Listening: deducir lo no dicho"],tasks:["Gramática: unidad 7","18 transformaciones con modales","Vocabulario: 40 tarjetas del mazo Núcleo B2","Escribir 180 palabras especulando sobre una noticia","Speaking: describir dos fotos y especular, 1 min"]},
 {n:14,t:"Relativas y frases complejas",gram:["Defining vs non-defining","whose, where, when, which referido a toda la frase","Relativas reducidas: the man sitting there"],lex:["Definir, precisar y añadir información"],skill:["Reading: multiple matching, técnica de barrido"],tasks:["Gramática: unidad 13","Combinar 15 pares de frases con relativa","Vocabulario: 40 tarjetas del mazo Formación de palabras","Escribir 180 palabras con al menos 4 relativas distintas","Registrar 5 errores"]},
 {n:15,t:"Causativo, conectores y concesión",gram:["have / get something done","although / though / even though / despite / in spite of","however, nevertheless, whereas, while"],lex:["Contraste y matización","Servicios y externalización"],skill:["Writing: cohesión y párrafos que enlazan"],tasks:["Gramática: unidades 11 y 16","20 ítems de open cloze centrados en conectores","Vocabulario: 40 tarjetas","Escribir un essay de 180 palabras a favor y en contra","Revisar cohesión del texto anterior con la lista de control"]},
 {n:16,t:"Formación de palabras",gram:["Prefijos negativos: un-, in-, im-, ir-, dis-, mis-","Sufijos de sustantivo, adjetivo, adverbio y verbo","Cambios de raíz irregulares"],lex:["30 familias léxicas de alta frecuencia en el examen"],skill:["Use of English parte 3: leer la frase entera antes de decidir"],tasks:["Gramática: unidad 16","30 ítems de word formation","Vocabulario: mazo Formación de palabras, dos pasadas","Escribir 160 palabras usando 10 derivados nuevos","Simulacro parcial de Use of English"]},
 {n:17,t:"Inversión, énfasis y cleft sentences",gram:["Inversión tras adverbios negativos","What / All / The thing that… cleft sentences","It was … that / who"],lex:["Énfasis y jerarquía de ideas"],skill:["Speaking: sonar preciso sin sonar memorizado"],tasks:["Gramática: unidad 17","15 transformaciones con inversión","Vocabulario: 40 tarjetas del mazo Falsos amigos","Escribir 180 palabras usando 3 estructuras enfáticas","Speaking Parte 4: opinión sostenida, 2 min"]},
 {n:18,t:"Segundo control y ajuste fino",gram:["Repaso de unidades 7, 11, 13, 16 y 17"],lex:["Vaciar cajas 1 y 2; repasar caja 3"],skill:["Autoevaluación con rúbrica en las dos tareas de Writing"],tasks:["Simulacro completo cronometrado y comparar con la semana 12","Reescribir tu peor texto aplicando toda la corrección","Speaking: 14 minutos completos, grabados","Actualizar el cuaderno de errores y eliminar los ya superados","Confirmar inscripción al examen si aún no lo hiciste"]}]},
{id:"D",name:"Bloque D · Formato, velocidad y nervios",wk:"Semanas 19–24",goal:"Ya tienes el nivel. Ahora se entrena el examen: tiempos, formato de cada parte, estrategia de respuesta y resistencia.",weeks:[
 {n:19,t:"Reading & Use of English contra el reloj",gram:["Repaso dirigido según fallos del último simulacro"],lex:["Léxico de los distractores típicos"],skill:["Reparto de tiempo por parte y orden de ataque"],tasks:["Cronometrar cada parte por separado y anotar minutos reales","Simulacro de Use of English completo","Vocabulario: repaso de todas las cajas","Analizar cada fallo: ¿nivel, lectura apresurada o desconocimiento?","Registrar los patrones de error"]},
 {n:20,t:"Writing: las dos tareas en 80 minutos",gram:["Estructuras de alto valor por tipo de texto"],lex:["Banco de frases por tarea: essay, review, report, proposal, email"],skill:["Planificar en 5 minutos, escribir en 30, revisar en 5"],tasks:["Escribir un essay y un review en tiempo real","Autoevaluar con la rúbrica antes de pedir corrección","Corregir con el Módulo 07 y reescribir","Memorizar 12 frases de andamiaje","Comparar tu texto con el modelo del módulo"]},
 {n:21,t:"Listening: las cuatro partes",gram:["Formas contraídas y débiles en habla rápida"],lex:["Paráfrasis: cómo el examen nunca repite la palabra del audio"],skill:["Multiple choice, sentence completion y multiple matching"],tasks:["Un test de listening completo al día, cuatro días","Escuchar dos veces y solo entonces leer el transcript","Anotar 10 paráfrasis nuevas por sesión","Shadowing de 5 minutos diarios","Registrar sonidos que no distingues"]},
 {n:22,t:"Speaking: las cuatro partes con compañero",gram:["Lenguaje funcional: acordar, discrepar, matizar, ganar tiempo"],lex:["Fillers naturales y frases de transición"],skill:["Interacción: escuchar y responder, no monologar"],tasks:["Ensayar las 4 partes con un compañero o en voz alta, 3 veces","Grabarte y transcribirte una vez","Evaluar tu transcripción con los criterios del examinador","Trabajar los 5 sonidos que peor te salen","Preparar 10 opiniones sobre temas frecuentes"]},
 {n:23,t:"Simulacro general y análisis",gram:["Solo repaso de errores recurrentes"],lex:["Solo repaso; no se aprende vocabulario nuevo esta semana"],skill:["Examen completo en condiciones reales"],tasks:["Simulacro completo el mismo día de la semana y a la misma hora que tu examen","Corregir en frío al día siguiente","Clasificar los fallos en: nivel, formato, tiempo o nervios","Trabajar únicamente la categoría más grande","Dormir y comer como lo harás el día del examen"]},
 {n:24,t:"Semana del examen",gram:["Nada nuevo. Repaso ligero de tus 20 errores más frecuentes"],lex:["Solo tarjetas de caja 1 y 2, 15 minutos al día"],skill:["Rutina, no esfuerzo"],tasks:["Bajar el volumen: máximo 30 minutos al día","Releer tus textos corregidos, no escribir nuevos","Confirmar sede, hora, documento y material permitido","Un listening y un speaking cortos cada día para no perder el oído","Descansar el día anterior; no estudiar después de las 20:00"]}]}
];
