import type { ReadingText, Strategy } from "./types";

export const READTEXT: ReadingText = {
 title:"The myth of the language gene",
 body:[
 "For decades, the idea that some people are simply 'good at languages' has been repeated so often that it is rarely questioned. Yet when researchers have tried to isolate a specific talent for language learning, the results have been consistently underwhelming. Aptitude tests do predict how quickly beginners progress in the first few months, but their predictive power fades almost entirely after the first year of serious study.",
 "What replaces it is far less glamorous. In a long-running study of adult learners in Sweden, the strongest predictor of eventual proficiency was not any measure of memory or musical ear, but the number of hours learners spent producing the language rather than consuming it. Those who wrote and spoke regularly, even badly, outperformed those who read and listened far more but rarely produced anything themselves. The researchers were careful to note that this was not simply a matter of motivation: several highly motivated participants who studied intensively made little progress because their study consisted almost entirely of passive review.",
 "There is a second, less comfortable finding. Learners who were corrected consistently improved faster than those who were not, but only when the correction was specific. Being told that a sentence 'sounds odd' produced almost no measurable change; being told which structure was wrong and why produced a lasting one. This may explain why so many learners plateau after reaching a level at which they can be understood: once communication succeeds, nobody bothers to correct them, and errors that were once temporary quietly become permanent.",
 "None of this means that individual differences are irrelevant. Working memory does appear to matter for listening, and learners with previous experience of a related language start from an obvious advantage. But these factors shift the timetable rather than the destination. The uncomfortable conclusion of the research is that most adults who fail to learn a language have not been defeated by their aptitude; they have been defeated by a method that felt like studying without ever requiring them to produce anything difficult."
 ],
 qs:[
 {q:"What does the writer say about aptitude tests?",o:["They are unable to predict progress at any stage.","Their usefulness is limited to the early stages of learning.","They measure motivation rather than ability.","They have been shown to be unreliable for beginners."],a:1,e:"Párrafo 1: predicen los primeros meses pero su poder «fades almost entirely after the first year». La opción correcta parafrasea, no repite. Ese es el patrón del examen: la respuesta nunca usa las palabras del texto."},
 {q:"The Swedish study found that successful learners were distinguished by",o:["a better memory for vocabulary.","the total number of hours they studied.","how much language they produced themselves.","their level of motivation."],a:2,e:"«the number of hours learners spent producing the language rather than consuming it». La opción D es un distractor explícito: el texto niega que fuera cuestión de motivación."},
 {q:"Why does the writer mention the highly motivated participants?",o:["To show that motivation guarantees progress.","To show that the type of study matters more than the effort put in.","To criticise the design of the study.","To explain why the study lasted so long."],a:1,e:"Pregunta de propósito: hay que preguntarse «¿para qué está esa frase aquí?». Sirve para descartar la motivación como explicación."},
 {q:"According to the third paragraph, correction only helps when it",o:["comes from a qualified teacher.","is given immediately.","identifies the exact problem.","is repeated many times."],a:2,e:"«only when the correction was specific… which structure was wrong and why». Las otras tres son plausibles en el mundo real pero no están en el texto: en Reading solo vale lo que el texto dice."},
 {q:"The word 'plateau' in the third paragraph suggests that learners",e:"Vocabulario en contexto: la frase siguiente explica el sentido («errors… become permanent»). Nunca busques la palabra en el diccionario mental: busca la explicación en la frase de al lado.",o:["improve suddenly.","stop making progress.","lose what they had learned.","become more confident."],a:1},
 {q:"What is the writer's main conclusion?",o:["Individual differences in aptitude do not exist.","Adults cannot learn languages as well as children.","Failure is usually caused by how people study, not by talent.","Most language courses are badly designed."],a:2,e:"La conclusión está en la última frase: «defeated by a method… without ever requiring them to produce anything difficult». La opción A exagera (el texto admite diferencias) y la D generaliza más allá del texto."}
 ]
};
export const STRATS: Strategy[] =[
 {t:"Listening · el protocolo de tres pases",b:["<b>Pase 1 — sin texto.</b> Escucha entero sin pausar. Solo idea general. Si no entiendes, no pasa nada: es el objetivo.","<b>Pase 2 — con las preguntas delante.</b> Ahora escuchas buscando información concreta. Pausa solo al final de cada sección.","<b>Pase 3 — con transcript.</b> Lee mientras escuchas y marca cada punto donde tu oído no reconoció algo que sí conoces por escrito. Eso, y no el vocabulario nuevo, es tu problema real.","<b>Después:</b> anota 10 paráfrasis. El examen nunca repite la palabra del audio en la pregunta: si el audio dice <i>I couldn't make it</i>, la opción dirá <i>he failed to attend</i>."]},
 {t:"Listening · lo que de verdad no oyes",b:["<b>Formas débiles:</b> <i>can</i> /kən/, <i>to</i> /tə/, <i>of</i> /əv/, <i>and</i> /ən/. No son sonidos nuevos: son los mismos, comprimidos.","<b>Enlaces:</b> <i>an apple</i> suena /əˈnæpl/, <i>what do you</i> suena /wɒdʒə/.","<b>Contracciones dobles:</b> <i>I'd've</i>, <i>shouldn't've</i>, <i>there'll</i>.","<b>Shadowing, 5 minutos:</b> repite en voz alta medio segundo por detrás del audio. Es el único ejercicio que arregla las tres cosas de arriba a la vez."]},
 {t:"Reading · orden de ataque",b:["<b>1. Lee las preguntas primero</b>, no las opciones. Las opciones contaminan tu lectura.","<b>2. Skim del texto en 90 segundos</b> para el mapa general: de qué va cada párrafo.","<b>3. Localiza y lee en detalle</b> solo el fragmento que responde a cada pregunta.","<b>4. Justifica con el texto.</b> Si no puedes señalar la línea exacta, no es la respuesta: es tu conocimiento del mundo.","<b>5. Descarta activamente.</b> En B2, tres opciones son verdad a medias: una exagera, otra invierte una relación causal, otra dice algo cierto pero que no responde la pregunta."]},
 {t:"Dieta semanal de entrada",b:["<b>Diario, 20 min:</b> un podcast con transcript. BBC Learning English · The English We Speak · All Ears English para B1; Hidden Brain, 99% Invisible o cualquier podcast técnico de tu sector para B2.","<b>3 días/semana:</b> un artículo de 600–900 palabras. The Guardian, BBC News, Ars Technica. Subraya 10 colocaciones, no palabras sueltas.","<b>2 días/semana:</b> 20 minutos de serie con subtítulos <i>en inglés</i>. Nunca en español: los subtítulos en tu idioma apagan el oído.","<b>1 día/semana:</b> un vídeo técnico de tu campo sin subtítulos. Toleras no entenderlo todo; ese es el ejercicio.","<b>Regla:</b> el material debe ser un poco difícil pero seguible. Si entiendes el 100%, no entrenas; si entiendes menos del 50%, no aprendes."]}
];
