import type { SpeakingPart } from "./types";

export const SPEAK: SpeakingPart[] =[
{id:"sp1",name:"Parte 1 · Entrevista",time:120,lvl:"2 min",
 what:"El examinador te hace preguntas personales sencillas. No es una conversación profunda: es un calentamiento donde demuestras fluidez y naturalidad. Responde en 2–3 frases, nunca en una sola palabra.",
 tips:["Amplía siempre: respuesta + razón + ejemplo o contraste.","Evita respuestas memorizadas: se notan y bajan la nota.","Si no entiendes, pide repetición en inglés: <i>Sorry, could you repeat that?</i>","No corrijas cada error: reformula y sigue."],
 lang:["Well, actually…","I'd say… mainly because…","It depends on…","That's a good question. I suppose…","I've been doing that for about…"],
 prompts:["Where are you from and what do you like most about living there?","Do you prefer working in the morning or in the evening? Why?","How do you usually spend your weekends?","Tell me about something you've learned recently.","Do you use English at work? In what situations?","What kind of music do you listen to while you work?"]},
{id:"sp2",name:"Parte 2 · Monólogo con fotos",time:60,lvl:"1 min",
 what:"Recibes dos fotografías y una pregunta que las compara. Hablas un minuto sin interrupción. No describes las fotos: las comparas y especulas.",
 tips:["Compara desde la primera frase, no describas cada foto por separado.","Especula con modales: <i>they might be…</i>, <i>it looks as if…</i>","Responde también a la segunda parte de la pregunta.","Si te quedas sin ideas antes del minuto, especula sobre cómo se sienten las personas."],
 lang:["Both photos show… but the main difference is that…","Whereas in the first one…, in the second…","They might be… , judging by…","It looks as though…","I'd imagine that…","Personally, I'd find the second situation more…"],
 prompts:["Compare these two ways of studying (alone at home / in a group at a library) and say which you think is more effective and why.","Compare two workplaces (an open-plan office / working from a kitchen table) and say which would be harder to concentrate in.","Compare two ways of travelling to work (by bicycle / on a crowded train) and say how the people might be feeling.","Compare two kinds of celebration (a large party / a quiet dinner) and say why people choose each one."]},
{id:"sp3",name:"Parte 3 · Tarea colaborativa",time:180,lvl:"3 min",
 what:"Con otro candidato discutes cinco opciones alrededor de una pregunta durante dos minutos, y luego tenéis un minuto para decidir juntos. Se evalúa la interacción: escuchar, responder, discrepar con educación.",
 tips:["No monologues: pregunta la opinión del otro cada 20–30 segundos.","No decidas antes de tiempo: hay que discutir todas las opciones primero.","Discrepar bien puntúa: <i>I see your point, but…</i>","En el minuto final, negocia de verdad; no basta con «yes, I agree»."],
 lang:["Shall we start with…?","What do you think about…?","That's a fair point, although…","I see what you mean, but I'm not sure that…","So, are we agreed that…?","Let's rule that one out, then."],
 prompts:["A company wants to help employees improve their English. Talk together about how effective these ideas would be: paying for private classes · a weekly English-only meeting · funding certificates · a language exchange with a partner office · subtitled training videos. Then decide which two would work best.","A city wants to reduce traffic. Discuss: free public transport · higher parking fees · more cycle lanes · remote-work incentives · pedestrian-only centre. Then decide which single measure to implement first.","A university wants to improve student wellbeing. Discuss: longer library hours · free sports facilities · smaller class sizes · mental-health counselling · flexible deadlines. Then choose two."]},
{id:"sp4",name:"Parte 4 · Discusión",time:240,lvl:"4 min",
 what:"El examinador amplía el tema de la parte 3 con preguntas más abstractas. Aquí se demuestra rango: opiniones matizadas, ejemplos y estructuras complejas.",
 tips:["Da tu opinión y justifícala con una razón y un ejemplo. Tres frases mínimo.","Reconoce la otra postura antes de rebatirla: sube la nota en Discourse Management.","Usa conectores de matiz: <i>admittedly, having said that, to a certain extent</i>.","Si el examinador se dirige a los dos, responde y luego pásale la palabra al otro candidato."],
 lang:["To a certain extent, yes, but…","Admittedly, …","Having said that, …","It very much depends on whether…","I'd go so far as to say that…","There's a lot to be said for…"],
 prompts:["Do you think employers should be responsible for their employees' training?","Is it possible to learn a language well without living in the country where it is spoken?","Some people say technology has made us worse at concentrating. Do you agree?","Should certificates matter more than experience when applying for a job?","Will artificial intelligence change the way we learn languages?"]}
];
